apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ac15
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: arenaclients
  source:
    repoURL: 'https://github.com/danielvschoor/aiarena-infrastructure'
    path: arenaclients/ac15
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: arenaclients