apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ac19
  namespace: arenaclients
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/danielvschoor/aiarena-infrastructure'
    path: arenaclients/ac19
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: arenaclients