apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ac21
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: arenaclients
  source:
    repoURL: 'https://github.com/danielvschoor/aiarena-infrastructure'
    path: arenaclients/ac21
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: arenaclients