apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: ac1
  target:
    kind: Deployment
    name: .*
  
- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: ARENA_CLIENT_ID
        value: "2"
  target:
    kind: Deployment
    namespace: arenaclients
    name: .*

- patch: |-
    - op: add
      path: "/spec/template/spec/containers/0/env/-"
      value:
        name: API_TOKEN
        valueFrom:
          secretKeyRef:
            key: ac2
            name: arenaclient-api-keys
            optional: false
  target:
    kind: Deployment
    namespace: arenaclients
    name: .*

  
namespace: arenaclients
metadata:
  name: ac2

commonLabels:
  app: ac2

