apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: arenaclients
  name: placeholder
  labels:
    app: placeholder
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: placeholder
  strategy:
    type: Recreate
  template:
    metadata:
        labels:
          app: placeholder
    spec:
      containers:
      - env:
        - name: PLACEHOLDER
          value: PLACEHOLDER
        image: aiarena/arenaclient
        imagePullPolicy: IfNotPresent
        name: arenaclient
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /root/aiarena-client/config.py
          name: config
          subPath: config.py
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          items:
          - key: config.py
            path: config.py
          name: arenaclient-production-config
          optional: false
        name: config