apiVersion: apps/v1
kind: Deployment
metadata:
  name: ac1
  namespace: arenaclients
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
  strategy:
    type: Recreate
  template:
    metadata:
    spec:
      containers:
      - env:
        - name: ARENA_CLIENT_ID
          value: ac1
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              key: ac1
              name: arenaclient-api-keys
              optional: false
        image: aiarena/arenaclient
        imagePullPolicy: IfNotPresent
        name: ac1
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: {}
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /root/aiarena-client/config.py
          name: config
          subPath: config.py
      dnsPolicy: ClusterFirst
      hostAliases:
      - hostnames:
        - aiarena.net
      nodeName: rancher
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 256
          items:
          - key: config.py
            path: config.py
          name: arenaclient-production-config
          optional: false
        name: config

