apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: arenaclients-master
  namespace: arenaclients
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    name: in-cluster
  project: arenaclients
  source:
    path: apps
    repoURL: 'https://github.com/danielvschoor/aiarena-infrastructure'
    targetRevision: HEAD